project_id = "qscyapmuiqaijvuitlyv"

[functions.delete-user]
verify_jwt = true

[functions.send-cancellation-notification]
verify_jwt = true

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-delivery-confirmation]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = true

[functions.send-subscription-notification]
verify_jwt = true
